### ISSUE TITLE
Support PopupAnchor features

### ISSUE THREAD

**Issue by wassimz** [mstahv/v-leaflet#102]
When a custom marker icon is used (within the setIcon function) and the marker popup is enabled, we need sometimes to set the popup anchor. This feature is already support by leaflet js framework and not yet by this addon. It will be great to support it.

Thanks

**Comment by octavm** [comment]
Workaround to set the popup anchor: 
Create a PopupState object, set its offset to where you'd like the Popup anchor to be. Then use the LMarker.setPopupState() method to apply the PopupState to the LMarker.

**Comment by wassimz** [comment]
It works.

Thanks
