### ISSUE TITLE
noWrap not working

### ISSUE THREAD

**Issue by ssaarinen** [mstahv/v-leaflet#103]
Setting layer to noWrap seems to have no effect (or I'm misinterpreting what nowrap should do). Tested this with ContinuousWorld in demoandtestapp in trunk. Screen shot attached.
![2015-10-22 13_31_21-mozilla firefox](https://cloud.githubusercontent.com/assets/384839/10663105/6c8301ca-78c1-11e5-96b9-0aea36513f5c.png)

**Comment by mstahv** [comment]
Updating to latest LeafletJS (https://github.com/mstahv/g-leaflet/commit/fde923908aa770a030f300a7c9fff4e06d2ce9bc) seems to fix this. There is though sometimes "broken image icons" for the "tiles" outside -190/190. If the tiles with "broken image icons" are a problem to you, create an issue to Leaflet project.

The continuousWorld option seems to have disappeared completely from LeafletJS (although still in documentation). No idea whether this is dropped or forgotten feature. Created an issue about that: https://github.com/Leaflet/Leaflet/issues/4024 . Need to update GWT/Vaadin API once we get more information from the maintainers.
