### ISSUE TITLE
Set Layer Control as collapsed (true|false)

### ISSUE THREAD

**Issue by prsebastian** [mstahv/v-leaflet#104]
Hi, 

the layers control is by default collapsed which I wanted to change, but apparently there seems to be no way for that. The original Leaflet documentation mentions that there is an option for that: http://leafletjs.com/reference.html#control-layers 

"collapsed (Type:Boolean, default true) If true, the control will be collapsed into an icon and expanded on mouse hover or touch."

But I have no idea on how to set it to false on v-leaflet's LLayers. The only option there is position. Can you help me out? I even don't find where the LeafletMouseOverLisenter resides which controls the behavior.

Thanks in advance
Sebastian

**Comment by mstahv** [comment]
The fix by @octavm is now merged in, the feature will be available in the next release. Thanks!
