### ISSUE TITLE
Box Zoom rectangle not displayed

### ISSUE THREAD

**Issue by octavm** [mstahv/v-leaflet#106]
When doing box zoom by dragging a rectangular area with the mouse, while pressing shift, the rectangle is not displayed. 

Looks like a regression issue which was already fixed in Leaflet (https://github.com/Leaflet/Leaflet/issues/3633).

Probably, the leaflet.css from g-leaflet needs to be updated to include some of these new 1.0-beta2 fixes.

**Comment by mstahv** [comment]
Fixed in https://github.com/mstahv/g-leaflet/commit/dd5cf3478b7f4124dc5a22f824d8558e61ce48de

**Comment by mstahv** [comment]
Thanks, awesome fixes, keep them coming.
