### ISSUE TITLE
Authentication/Tokens

### ISSUE THREAD

**Issue by myio561** [mstahv/v-leaflet#108]
Is there a way for me to request (authenticate) and the provide an access token with this addon?

**Comment by mstahv** [comment]
Do you have some examples how it should work? E.g. a plain JS example would be fine.

cheers,
matti

**Comment by myio561** [comment]
I decided to just use the ArcGIS Javascript interface. It looks like the problem isn't an authentication issue, but just how the maps have been published here.

**Comment by mstahv** [comment]
Cool, did you create some sort of Vaadin wrapper for it? It would be cool to have it as an add-on to [Directory](https://vaadin.com/directory/).

Also, if there is anything that can help v-leaflet usage with ArcGIS server to become easier, let me know if I can help.

**Comment by myio561** [comment]
I just made the most basic wrapper using the AbstractJavaScriptComponent. I’m sure I will add functionality to this over time.

Scala class
```scala
@StyleSheet(Array(
    "https://js.arcgis.com/3.15/dijit/themes/claro/claro.css",
    "https://js.arcgis.com/3.15/esri/css/esri.css"))
@JavaScript(Array("https://js.arcgis.com/3.15", "Vesri.js"))
class Vesri extends AbstractJavaScriptComponent {
    setId("ArcGISMap")
    setSizeFull()
    setImmediate(true)
}
```

Javascript
```javascript
com_nextera_fim_ventus_component_Vesri = function() {

    var map;
    require([
        "esri/map",
        "esri/layers/ArcGISDynamicMapServiceLayer",
        "dojo/domReady!"], function(Map, ArcGISLyr) {
        map = new Map("ArcGISMap", {
            center: [-56.049, 38.485],
            zoom: 5,
            basemap: "streets"
        });

        // TODO: Read in this URL from a config file
        var lyr = new ArcGISLyr("http://myserver/rest/services/MapServer");
        map.addLayer(lyr);
    });

}
```
