### ISSUE TITLE
LTileLayer URL format for GeoServer connection

### ISSUE THREAD

**Issue by sempervivo** [mstahv/v-leaflet#119]
Hi,

I installed a geoserver on our local intranet and now I want to get the maps from it using this addon. My problem is that I didn't find a real example of a good url format for the class LTileLayer. Until now I only found the format http://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png, which doesn't work with my geoserver. Do you have a working example on how to get the data from a geoserver ?

Thank you.

**Comment by sempervivo** [comment]
Doesn anybody know how to setup the TileLayer URL and its properties in order to successfully connect to a geoserver ?

**Comment by warwickdufour** [comment]
Hi,

My understanding is that GeoServer doesn't directly support 'slippy map' requests from v-leaflet's LTileLayer component. Instead you have to use v-leaflet's LWmsLayer component to perform WMS requests to GeoServer. This works for us although you can see LWmsLayer performing mulitple WMS requests to fetch tiles 'under the bonnet'. As far as I know there is know way to switch the tiling behaviour of v-leaflet off.

Regards,

Warwick

**Comment by mstahv** [comment]
I'm not a geoserver expert, but I think @warwickdufour is right and by default geoserver only provides WMS formatted output, which can be consumed with LWmsLayer. WTileLayer is for TMS.

tileSize property should have an effect on how big tiles are fetched form TMS and WMS services. I don't remember if there is a Java api for it, but should be really easy to add if not.

http://leafletjs.com/reference.html#tilelayer-tilesize

**Comment by sempervivo** [comment]
Thank you all. I managed to consume it with LWmsLayer. It's pretty straightforward, as long as one knows what class to use ;)

**Comment by mstahv** [comment]
We should indeed start to build a proper documentation for the project. I created [a wiki] which can be used as a starting point. If you got inspired, feel free to start the effort.

https://github.com/mstahv/v-leaflet/wiki
