### ISSUE TITLE
Add custom css style to LMarker

### ISSUE THREAD

**Issue by VivekG03** [mstahv/v-leaflet#129]
It should be able to add a custom css style to LMarker by using addStyleName / setStyleName

**Comment by dominic-simplan** [comment]
+1. The addStyleName method is available on LMarker, however any values which are set this way are ignored. The style name is not applied to the marker element 😢

**Comment by mstahv** [comment]
classnames now are attached to dom if it is an SVG marker or if custom marker icon is used. Would somebody need custom style name for the default marker? If so, please re-open and let's see if we can figure out something for that.
