### ISSUE TITLE
Enhancement request: Support LMarker zIndexOffset feature

### ISSUE THREAD

**Issue by amwilcox** [mstahv/v-leaflet#130]
Leaflet's LMarker has a zIndexOffset option to allow control of the zIndex of specific markers. 

This is a request to update the g-leaflet and v-leaflet add-ons to support the setting of zIndexOffset for LMarker..

**Comment by mstahv** [comment]
Closed in [17f8a671554ec82f757abc8f15b927b63a4e56c2]
