### ISSUE TITLE
Support for Zoomify Images

### ISSUE THREAD

**Issue by dve** [mstahv/v-leaflet#154]
Hi,
I tried to add support for [Leaflet.Zoomify](https://github.com/turban/Leaflet.Zoomify) but I failed :-(
Could you maybe take a look on it and give me a hint?
My try is located here: https://github.com/vegetweb/v-leaflet-zoomify and https://github.com/vegetweb/g-leaflet-zoomify

Thanks

Daniel

**Comment by mstahv** [comment]
I quickly tried this, but it gave me some JS exceptions about missing g parameter. All look good to me. Maybe an issue with the latest Leaflet? The Zoomify plugin itself looks bit old.

Maybe you could use the basic tile layer instead? Don't know what is the easiest way to create tilesets though, Zoomify might be easier to use than other solutions.

**Comment by dve** [comment]
The layer works with the latest leaflet (1.2.0): https://github.com/vegetweb/zoomify-demo

We already have al large amount of pictures as zoomify tiles, so we can not change this.

**Comment by mstahv** [comment]
OK, then it is hopefully just a matter of updating the v-leaflet to have latest LeafletJS. I have had no time to look at any community efforts lately :-( I'll try to look at this later today.

**Comment by dve** [comment]
The error keeps the same with leaflet 1.2.0

**Comment by mstahv** [comment]
It sure wasn't version conflict. Had to take one beer and debug this. It was actually just one cast missing -> call was going to wrong method -> it tried to create normal tile layer. 

Change [this line](https://github.com/vegetweb/v-leaflet-zoomify/blob/master/v-leaflet-zoomify-addon/src/main/java/org/vaadin/addon/leafletzoomify/client/LZoomifyLayerConnector.java#L30) into this:

    return ZoomifyLayer.create(getState().url, (ZoomifyLayerOptions) o);

**Comment by mstahv** [comment]
BTW. I'd suggest to use this archetype as a basis for the v-leaflet-zoomify addon: https://github.com/viritin/archetype-vaadin-gwt-addon Makes development and debugging much easier than with the "official" widget archetype.

**Comment by dve** [comment]
Thank you and your beer a lot! If you come to north or north-eastern germany I would be glad to return the beer to you.

I will look at the new archtype and update the addon before submitting it. 

Why is the "handy" stuff not the official one a vaadin?

**Comment by dve** [comment]
I've made all the changes and published to [vaadin directory](https://vaadin.com/directory#!addon/lzoomifylayer-add-on). The code has moved to https://github.com/infinitenature/v-leaflet-zoomify

Thanks a lot!
