### ISSUE TITLE
LImageOverlay listeners not working

### ISSUE THREAD

**Issue by strxetics** [mstahv/v-leaflet#184]
click, contextclick, contextmenu and mouseover listeners are never called for my LImageOverlay.
LMarker listeners are working fine.

is there a trick or is this a bug?

Version: 2.0.7

**Comment by octavm** [comment]
Fixed in Vaadin-7 compatible branch.
I can port the fix to Vaadin-8 (master) branch too, if there's a need for it.

**Comment by strxetics** [comment]
I would be really happy if you did :)

**Comment by octavm** [comment]
Ok, I've added the fix to master branch. Now its up to @mstahv to accept the merge and maybe cut a new release.

**Comment by strxetics** [comment]
@octavm thank you :)
