### ISSUE TITLE
zoomSnap not implemented

### ISSUE THREAD

**Issue by strxetics** [mstahv/v-leaflet#190]
It would be great if someone could make a pass through of the zoomSnap feature

https://leafletjs.com/reference-1.3.2.html#map-zoomsnap

with the current implementation with only integer steps, it is hardly possible to render images on a crs.simple layer so that they fill the whole screen on different resolutions because the zoomsteps are too big.

**Comment by octavm** [comment]
I've created a pull request to get the zoomSnap feature implemented.
