### ISSUE TITLE
Make Map#getSize  available in v-leaflet

### ISSUE THREAD

**Issue by dve** [mstahv/v-leaflet#223]
To send proper "GET_FEATURE_INFO" requests the size of the map is needed. leaflet supports it: https://leafletjs.com/reference.html#map-getsize

This should be available in v-leaflet

**Comment by dve** [comment]
I tried to get it working but no success yet:
https://github.com/dve/v-leaflet/tree/%23223_add_map_getsize
https://github.com/dve/g-leaflet/tree/add_map_getsize

**Comment by dve** [comment]
@mstahv I've found that I have to use rpc calls - please review an merge

**Comment by mstahv** [comment]
Reviewed, tested, released. Great work again @dve!
