### ISSUE TITLE
FontAwesome icons do not render on LMarkers

### ISSUE THREAD

**Issue by tmattsso** [mstahv/v-leaflet#57]
Trying the new FontAwesome icons out, I noticed that they don't work on markers.

GET fonticon://FontAwesome/f024 net::ERR_UNKNOWN_URL_SCHEME 

Client side not translating URL properly?

**Comment by mstahv** [comment]
Fontawesome icons are not images so they cannot be used as such in Leaflet. As a workaround these can be used with:

            lMarker.setDivIcon(FontAwesome.ARROW_DOWN.getHtml());

But something better will definitely be needed. Working on a "marker symbol" + white font awesome symbol on top of it.

**Comment by mstahv** [comment]
This kind of markers now appear if one just uses marker.setIcon(FontAwesome.BEER) :

<img width="115" alt="screenshot 2015-08-20 00 29 16" src="https://cloud.githubusercontent.com/assets/1478052/9369531/8c581fd8-46d2-11e5-8bf4-b179a8da4d55.png">

Need to improve customisability at some point.
