### ISSUE TITLE
Version 0.6.1 Widgetset does not compile

### ISSUE THREAD

**Issue by anwimafi** [mstahv/v-leaflet#75]
I am working on a standard vaadin application using the maven generated project (with submodules). When changing the v-leaflet dependency to version 0.6.1 (0.5.1 runs fine), the widgetset fails to compile:
[ERROR] Errors in 'jar:file:/C:/Users/Christian%20Freihoff/.m2/repository/org/vaadin/addon/v-leaflet/0.6.1/v-leaflet-0.6.1.jar!/org/vaadin/addon/leaflet/client/LeafletPolygonConnector.java'
         [ERROR] Line 14: The method createWithHoles(JsArray<JsArray<JsArray>>, PolylineOptions) is undefined for the type Polygon
      [ERROR] Errors in 'jar:file:/C:/Users/Christian%20Freihoff/.m2/repository/org/vaadin/addon/v-leaflet/0.6.1/v-leaflet-0.6.1.jar!/org/vaadin/addon/leaflet/client/LeafletPolylineConnector.java'
         [ERROR] Line 78: The method createWithArray(JsArray<JsArray>, PolylineOptions) is undefined for the type Polyline
   [ERROR] Aborting compile due to errors in some input files

**Comment by mstahv** [comment]
Have you explicitly defined g-leaflet version?

**Comment by anwimafi** [comment]
<dependency>
            <groupId>org.peimari</groupId>
            <artifactId>g-leaflet</artifactId>
            <version>0.4.8</version>
        </dependency>
        <dependency>
            <groupId>org.peimari</groupId>
            <artifactId>g-leaflet-draw</artifactId>
            <version>0.4.2</version>
        </dependency>

**Comment by mstahv** [comment]
Hi,

With 0.6.1 the g-leaflet version should be [0.4.9](https://github.com/mstahv/v-leaflet/blob/v-leaflet-0.6.1/pom.xml#L305).

Actually all you should need is the v-leaflet-draw dependency. Everything else (including gwt modules (g- prefixed) and v-leaflet ) should be drawn in transitively. That is currently in version 0.6.0, I should create a new release of that to update its dependencies (most essentially v-leaflet).

BTW. What kind of drawing features are you using? If you have advanced GIS features like real polygons (with holes) I'd urge to check out v-leaflet-editable. It provides pretty much all the same as the draw module, but is just more advanced in many ways. It don't have that "drawing toolbar" though, but you can naturally build a custom tailored version with Vaadin code.

cheers,
matti

**Comment by anwimafi** [comment]
Tanks Matti, 
I changed the dependencies, and it works :-)
At the moment I am only drawing points to a LMap and editing them by use of a pointfield. Next step would be free drawing of points and maybe polygons. I think Your example application should give me all the info I need for that.
By the way: there is one thing i cannot get running:
- a form with bindings to the underlying object, pointfield bound to geom, okay
- in addition textual representation of a points coordinates, bound to methods which pull the x/y out of the geom, marked as dirty by a valuechangedlistener added to the point field, okay
- change in the two coordinate textfields shall be reflected in the pointfield, tried to set new geom in the object, also repeated the binding procedure, marked pointfield as dirty, nothing changes. Also tried the setValue() of the pointfield, nothing changes. So, what would You suggest to achieve that (if i am satisfied with single point geom)?
