### ISSUE TITLE
Change markers' and popups' anchor

### ISSUE THREAD

**Issue by russellhoff** [mstahv/v-leaflet#77]
I have realised that, by default, the anchor of popups and markers is set to 0,0. Unfortunately, there is not method to modify it.

Can I do something regarding this issue?

Thank you :)

**Comment by russellhoff** [comment]
No answer? :(

**Comment by russellhoff** [comment]
I found a method on LMarker class called setIconAnchor(Point p), so it was what I needed. Closed & thanks!

**Comment by mstahv** [comment]
Great, sorry I have forgotten to answer.
