### ISSUE TITLE
implement image layer

### ISSUE THREAD

**Issue by bedinsky** [mstahv/v-leaflet#78]
Can v-leaflet be used for navigating non-map imagery?

You can do this with leaflet

You do have to convert your pixel sizes to latlng but Leaflet provides you an easy way to do that, by using the Simple "Coordinate Reference System", map.project and map.unproject.

Construct your map like this:

var map = L.map('map', {
  maxZoom: 20,
  minZoom: 20,
  crs: L.CRS.Simple
}).setView([0, 0], 20);
and then set the map bounds (where my image is 1024x6145):

var southWest = map.unproject([0, 6145], map.getMaxZoom());
var northEast = map.unproject([1024, 0], map.getMaxZoom());
map.setMaxBounds(new L.LatLngBounds(southWest, northEast));

Hi Matti ! 
if you tell me where to start from your code I could consider to implement image layer 
sorry that i did not understand rating system of vaadin directory !

**Comment by mstahv** [comment]
Hi,

I added an example how similar features can be added. So, first add the GWT API like in https://github.com/mstahv/g-leaflet/commit/7eaf5578fadf0097bf8f1869355c400b3b805277 , then create the server side wrapper with GWT connectors to v-leaflet. 

Can you try if the solution suits for your case? Build SNAPSHOT versions of both g-leaflet and v-leaflet projects. If it works I'll create a new release (I could also drag in latest changes from Leaflet 7.x branch). Then I'll start looking at upgrade to Leaflet JS 1.0 (soon to get a first beta release).

cheers,
matti

**Comment by mstahv** [comment]
BTW. If you plan to contribute new features, please create an issue here and tell what you are working on so there won't be collisions.

**Comment by bedinsky** [comment]
Hi Matti !
thank you very much for quick response ! I'll try to build add-ons and try
your solution
I need this feature inside my app to show some technical drawings.

bob



On Mon, Apr 13, 2015 at 4:27 PM, Matti Tahvonen <notifications@github.com>
wrote:

> Hi,
>
> I added an example how similar features can be added. So, first add the
> GWT API like in mstahv/g-leaflet@7eaf557
> <https://github.com/mstahv/g-leaflet/commit/7eaf5578fadf0097bf8f1869355c400b3b805277>
> , then create the server side wrapper with GWT connectors to v-leaflet.
>
> Can you try if the solution suits for your case? Build SNAPSHOT versions
> of both g-leaflet and v-leaflet projects. If it works I'll create a new
> release (I could also drag in latest changes from Leaflet 7.x branch). Then
> I'll start looking at upgrade to Leaflet JS 1.0 (soon to get a first beta
> release).
>
> cheers,
> matti
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/mstahv/v-leaflet/issues/78#issuecomment-92378746>.
>



-- 
“Think Green - Please do not print this email unless you really need to“

**Comment by mstahv** [comment]
This kind of usage should probably do it then:
https://github.com/mstahv/v-leaflet/blob/a0cb5f67e2bd68c1c68a2ce5bc891ec013c58983/src/test/java/PlainImage.java

Probably pretty common use case actually, I think I have heard somebody asking this kind of feature at some point earlier. Using v-leaflet-editable or v-leaflet-draw you can probably quite easily now add also simple commenting features as well so your users could highlight some areas and add comments regarding those.

cheers,
matti

**Comment by bedinsky** [comment]
Hi Matti !
I've tested v-leaflet 0.6.2-SNAPSHOT with g-leaflet 0.4.10-SNAPSHOT
using your example in a com.vaadin.navigator.View in my webapp.

It works unless image does not show the very first time, I hope it depends because of network download delay. 

I was able to add some markers but I do not know how to make them draggable.
I see a DragEndEvent but I've not found any implementation referring to it.
Is it implemented marked dragging?

Thank you very much, I'm looking forward for next release of v-leaflet !

**Comment by mstahv** [comment]
I think that is just the loading latency. It appears once its fully downloaded. An option might be good for UX to add a simple layer behind the large image that just has small image with text "Loading..." or something. I'll create a new release in a moment.

Just adding dragendlistener will make the marker "draggable". Like here:
https://github.com/mstahv/v-leaflet/blob/master/src/main/java/org/vaadin/addon/leaflet/util/PointField.java#L34

**Comment by bedinsky** [comment]
It works ! Thank you very much indeed !

**Comment by bedinsky** [comment]
Hi,
I've found an issue with markers and imageoverlay. 
Markers are not repositioned correctly changing zoom level.

These are the step
resize image using bound to fit screen width
set zoom level to zero
place a marker pointing to an image detail 
increase zoom level
marker is not pointing to image detail

Eventually I disable zoom with 
leafletMap.setMinZoom(0);
leafletMap.setMaxZoom(0);		
I would like to hide zoom control but I do not know how to do.
leafletMap.removeControl() want a LZoom but I do not have it

**Comment by mstahv** [comment]
Hi,

Do you have a test case you could contribute? Best if straight to this projects src/test/java/.... directory. That would help me to get this resolved.

cheers,
matti

**Comment by bedinsky** [comment]
Hi,

I'll use this source
https://github.com/mstahv/v-leaflet/blob/a0cb5f67e2bd68c1c68a2ce5bc891ec013c58983/src/test/java/PlainImage.java
to prepare a specific test


Bob






On Thu, Apr 30, 2015 at 12:33 PM, Matti Tahvonen <notifications@github.com>
wrote:

> Hi,
>
> Do you have a test case you could contribute? Best if straight to this
> projects src/test/java/.... directory. That would help me to get this
> resolved.
>
> cheers,
> matti
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/mstahv/v-leaflet/issues/78#issuecomment-97732907>.
>



-- 
“Think Green - Please do not print this email unless you really need to“

**Comment by mstahv** [comment]
Thanks, just copy that to a different test case and send me a pull request of it.

**Comment by bedinsky** [comment]
Hi,
I've updated v-leaflet to 0.6.4. It seems that zoom iusse has been fixed.
I'm sorry that I had not help you with a test but I had to switch to another project.
Thank you very much!
