### ISSUE TITLE
Creating LPolyline with null coordinates breaks something down

### ISSUE THREAD

**Issue by golimarrrr** [mstahv/v-leaflet#82]
I create about 150 lines in a loop which has this statement inside:

`polyLine = new LPolyline(Point a, Point z);`

And for one of the lines `a` and `z` are `null`. Of course that line is not created, but after that one no more lines appear on the map (I checked that the loop continues running and calling `new LPolyline` with correct values). Besides, calling `removeAllComponents()` on the `LLayerGroup` where the lines are contained does not remove them from the map.

I tried on 0.6.1 and 0.6.3.

**Comment by mstahv** [comment]
I'd not like to add a sanitising logic to be enabled by default as it adds some overhead. Maybe the helpers I prototyped in https://github.com/mstahv/v-leaflet/commit/6ba858fc8fa4a6cef2b7ab6798b0c75bca849ba4 would be a good compromise?

**Comment by golimarrrr** [comment]
Could you reproduce the issue? I'm not totally sure that something else in
my program could be the cause of this

2015-05-29 16:09 GMT+02:00 Matti Tahvonen <notifications@github.com>:

**Comment by mstahv** [comment]
Yes, it happens if you pass null values to geometries in both polyline and polygon. The Leaflet on client side don't like the nulls between there. As the geometries can be largish, I'd like to avoid iterating the whole point list to remove the nulls. Thus I added a helper method sanitizeGeometry() to remove possible null values.

**Comment by golimarrrr** [comment]
I think that will be enough. However if developers notice something strange they may not know the way to fix it... maybe issuing a warning additionally would be convenient?

**Comment by mstahv** [comment]
Yep, bit tricky in that sense, hard to find the issue :-( Throwing a sane warning would cost pretty much the same as doing the actual sanitising. A best solution might be to have an API to configure it off if performance becomes an issue. If you want to provide such a pull request, I'd be honoured to pull it in.

**Comment by mstahv** [comment]
Lets go with the this solution that is now in 0.6.4. It this appears to be a more common issue, we'll make sanitisation default and make it configurable to skip it.
