### ISSUE TITLE
Issue on displaying info on Popup

### ISSUE THREAD

**Issue by wassimz** [mstahv/v-leaflet#84]
Hi,

I have an application where I display marker and line together with popup info. I provide HTML table String to both of them. I have an issue that all popup window are using same size, and so when I display popup window with different text size, the text is outside the white box.

Please see attached some screenshot. You can see on second image the text is outisde the white box which is using the first image size.

![popup1](https://cloud.githubusercontent.com/assets/1709161/8208645/5c41d0c0-1511-11e5-8539-770e9054e1cd.png)
![popup2](https://cloud.githubusercontent.com/assets/1709161/8208644/5c41d94e-1511-11e5-9178-d9d6d6f8e55e.png)

**Comment by mstahv** [comment]
There would be max/minWidth in Leaflet Popup, but the API is still missing. Maybe that would do it for you:
http://leafletjs.com/reference.html#popup

As a quick workaround I'd use CSS to adjust the widths of the columns (maybe overflow some text).

**Comment by wassimz** [comment]
Thanks.

I have seen that there is a class PopupState that I can set from the LMarker class. But how I can use it ??

**Comment by mstahv** [comment]
Oh, it appears so. Added probably by some other contributor as I don't remember that. There appears to be actually two states for popups, one for those coupled to markers and other for "standalone" LPopup. Those should be combined.

You can probably just instantiate a PopupState, assign the values and then pass the object to LMarker. Something like:

    PopupState ps = new PopupState();
    ps.maxWidth = 1234;
    lMarker.setPopupState(ps);

**Comment by wassimz** [comment]
The above code works like a charm and fixes the issue.

Thanks for your helps.
