### ISSUE TITLE
Empty popup

### ISSUE THREAD

**Issue by wassimz** [mstahv/v-leaflet#85]
Hi,

How I can avoid having emtpy popup on a given marker.
Currently I want just my marker trigger a click listener on backend without opening the popup window.
Please see below picture
![emptypopup](https://cloud.githubusercontent.com/assets/1709161/8304516/462ac2cc-19af-11e5-9172-ec86e9a08009.png)

**Comment by mstahv** [comment]
Have you called public void setPopup(String popup) with empty string? The Popup shouldn't appear there if you have popup string as null, as it ought to be by default.

**Comment by wassimz** [comment]
Yes I have tried both setPopup(null) and setPopup("") and still I got the same result.

**Comment by mstahv** [comment]
Hi, I tried something like this and still cannot reproduce this:

        LMarker another = new LMarker(60.4525, 22.303);
        another.addClickListener(new LeafletClickListener() {

            @Override
            public void onClick(LeafletClickEvent event) {
                Notification.show("Another marker was clicke.");
            }
        });
        leafletMap.addComponent(another);

Could you prepare a test case that I could use to reproduce the issue. Also report the browser and OS you are using. Otherwise I cannot do a thing for this.

**Comment by wassimz** [comment]
Thanks for you replies. The issue was fixed from my side (in my code). The error was due to that at some place I am using setPopup("") which provide the empty popup info window. Changing this to setPopup(null) fixed the issue.

Thanks again
