### ISSUE TITLE
Map is only shown when its size set to PIXELS, not to PERCENTAGES

### ISSUE THREAD

**Issue by russellhoff** [mstahv/v-leaflet#86]
I've got a map in a Custom Component which I want it to occupy the full room of the layout (100%). Unfortunately, the map isn't shown when I specify its size that way:

		lMapa.setWidth("100%");
		lMapa.setHeight("100%");

Whenever I write the following code, the map is shown:

		lMapa.setWidth("100px");
		lMapa.setHeight("100px");

Why? Is that a bug?

**Comment by russellhoff** [comment]
The problem occurs when setting Height to Percentage, there is no trouble when assigning Percentage widths.

**Comment by mstahv** [comment]
Is all components around the map defined so that they have some "extra space" they can give for the actual map? CustomComponent itself and its parent and then so on? You might get some help using the the debug dialog opened with "?debug" query parameter.

**Comment by russellhoff** [comment]
What I have done is here: http://stackoverflow.com/questions/31028870/how-can-i-make-a-verticallayout-scrollable-using-vaadin

**Comment by mstahv** [comment]
Yep, so you probably do have your map now inside an undefined height layout -> map becomes 0px height. You most set either the vertical layout 100% height as well or place the map directly into your Panel.

**Comment by russellhoff** [comment]
Ah ok... I did it since I wanted that piece of screen to be scrollable vertically in case the height of the components within overpass the layout. Anyway it's good to know ;)

**Comment by mstahv** [comment]
Yep, hunded percent is measured from the amount that the layout can have to offer. Thus, 100% of 0px is 0px.
