### ISSUE TITLE
creating a Bounds object with the default constructor can create a wrong result

### ISSUE THREAD

**Issue by TheHaf** [mstahv/v-leaflet#89]
While trying to add an image overlay to a leaflet map, I noticed a bug with the current implementation. The default constructor does not initialize the internal corner variables. Calling the extend method on such a Bounds object can result in wrong bounds, depending on the coordinates. Here is an example:

``` java
import org.vaadin.addon.leaflet.shared.Bounds;
import org.vaadin.addon.leaflet.shared.Point;

public class BoundsTester {

    public static void main(String[] args) {

        // Test 1 - default constructor doesn't initialize corners and results in wrong bounds in some cases
        Bounds bounds = new Bounds();
        bounds.extend(new Point(25,25));
        bounds.extend(new Point(35,35));
        System.out.println("Test 1: " + bounds.toString());
        // -> Bounds{southWestLng=0.0, southWestLat=0.0, northEastLng=35.0, northEastLat=35.0}

        // Test 2 - default constructor also works in some cases
        bounds = new Bounds();
        bounds.extend(new Point(-25,-25));
        bounds.extend(new Point(35,35));
        System.out.println("Test 2: " + bounds.toString());
        // -> Bounds{southWestLng=-25.0, southWestLat=-25.0, northEastLng=35.0, northEastLat=35.0}

        // Test 3 - using the constructor with a Point parameter always works, as the corners are initialized correctly
        bounds = new Bounds(new Point(30,30));
        bounds.extend(new Point(25,25));
        bounds.extend(new Point(35,35));
        System.out.println("Test 3: " + bounds.toString());
        // -> Bounds{southWestLng=25.0, southWestLat=25.0, northEastLng=35.0, northEastLat=35.0}

        // Test 4 - setting the two internal corners to initial min/max values by hand also works
        bounds = new Bounds();
        bounds.setSouthWestLat(90);
        bounds.setSouthWestLon(180);
        bounds.setNorthEastLat(-90);
        bounds.setNorthEastLon(-180);
        bounds.extend(new Point(25,25));
        bounds.extend(new Point(35,35));
        System.out.println("Test 4: " + bounds.toString());
        // -> Bounds{southWestLng=25.0, southWestLat=25.0, northEastLng=35.0, northEastLat=35.0}
    }

}
```

**Comment by mstahv** [comment]
The fields in the class should probably be of type Double instead of double to allow such usage. Would you like to contribute and enhancement to it as you appear to have good use cases?

**Comment by TheHaf** [comment]
Even if the fields were of the type `Double`, they still would need to be initialized to a certain value, for instance to `Double.MIN_VALUE`/`Double.MAX_VALUE`, otherwise you get NullPointerExceptions with the current code. At first I thought about initializing them to the min/max values for latitude and longitude as shown in test 4, but now I think that this might also be a bad idea, at least for the longitude, since maps with `noWrap` set to `false` can have longitude values below -180 and above 180.

My proposal is to leave the type at `double` and add calls to the setters similar to the constructor with one Point parameter, but with the appropriate `Double.MIN_VALUE`/`Double.MAX_VALUE` values.

I can prepare a pull request for that proposal if that sounds ok to you.

**Comment by mstahv** [comment]
Hmm, -180,180,-90,90 defaults might work for most cases and shouldn't cause too many regressions? Still not a perfect solution. Another option would be to delete the problematic empty value constructor altogether, but that is potentially backwards incompatible.

Prepare a pull request, a real draft of the solution is often the best way to figure out the best solution.

**Comment by TheHaf** [comment]
I just prepared a pull request as a first draft. 
As a side note, while I was on it, I also created another pull request which adds support for JTS Coordinate arrays, as this is the base from which I am creating Bounds in my project. As V-Leaflet uses JTS in other places of its API, my guess would be that other people also want to use JTS objects as parameters in case of the Bounds class.
