### ISSUE TITLE
Bounding Box seems to be null after LMap initialization 

### ISSUE THREAD

**Issue by TimoSenger** [mstahv/v-leaflet#97]
It seems that the Bounding Box of a new initialized Lmap has no values. I had to zoom or pan to get correct bounding box values. 

How to reproduce (snippet):
	LMap leafletMap = new LMap();
	leafletMap.setCenter(0, 0);
	leafletMap.setZoomLevel(2.5);
	leafletMap.addLayer(new LOpenStreetMapLayer());
	Bounds b = leafletMap.getBounds();
	if(b==null){
		System.out.println("There seems to be something wrong");
	}

What did I do wrong? Or is it a bug?

**Comment by mstahv** [comment]
The bounding box is hard to know before the component is actually rendered. Especially if the map is fluid size (e.g. 100% width) like in most cases it is, it is impossible to know the exact bounds right after instantiation.

The workaround is to add LeafletMoveEndListener and do the stuff that needs exact bounds in it.

This definitely needs to be documented to javadocs, don't close this issue until it is done.
